// Generated by Lovable design-system attach. Do not edit by hand.
// Re-exports the components from this attached library so consumer
// imports through `@/design-system/{slug}` resolve uniformly.

export { Badge, Tag } from "./design-system/region17/components/Badge";
export { Button } from "./design-system/region17/components/Button";
export { Card } from "./design-system/region17/components/Card";
export { Checkbox, Radio, Switch } from "./design-system/region17/components/Checkbox";
export { ConfidenceFlag } from "./design-system/region17/components/ConfidenceFlag";
export { Field, Input, Select, Textarea } from "./design-system/region17/components/Field";
export { Icon } from "./design-system/region17/components/Icon";
export { IconButton } from "./design-system/region17/components/IconButton";
export { PanBand } from "./design-system/region17/components/PanBand";
export { RegionTag } from "./design-system/region17/components/RegionTag";
export { Seal } from "./design-system/region17/components/Seal";
export { SectionHeader } from "./design-system/region17/components/SectionHeader";
export { Statistic, StatisticBand } from "./design-system/region17/components/Statistic";
