/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/.lovable/oauth/consent'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/.lovable/oauth/consent'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/.lovable/oauth/consent'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
