/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as JoinEnRouteImport } from './routes/join/en'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as LocaleVerifyRouteImport } from './routes/$locale/verify'
import { Route as LocaleSigninRouteImport } from './routes/$locale/signin'
import { Route as LocaleHomeRouteImport } from './routes/$locale/home'
import { Route as LocaleDeclareRouteImport } from './routes/$locale/declare'
import { Route as LocaleJoinIndexRouteImport } from './routes/$locale/join/index'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LocaleJoinRegisterRouteImport } from './routes/$locale/join/register'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const JoinEnRoute = JoinEnRouteImport.update({
  id: '/join/en',
  path: '/join/en',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleVerifyRoute = LocaleVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSigninRoute = LocaleSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleHomeRoute = LocaleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDeclareRoute = LocaleDeclareRouteImport.update({
  id: '/declare',
  path: '/declare',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleJoinIndexRoute = LocaleJoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleJoinRegisterRoute = LocaleJoinRegisterRouteImport.update({
  id: '/join/register',
  path: '/join/register',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/$locale/declare': typeof LocaleDeclareRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/signin': typeof LocaleSigninRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/join/en': typeof JoinEnRoute
  '/$locale/': typeof LocaleIndexRoute
  '/join/': typeof JoinIndexRoute
  '/$locale/join/register': typeof LocaleJoinRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/$locale/join/': typeof LocaleJoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/$locale/declare': typeof LocaleDeclareRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/signin': typeof LocaleSigninRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/join/en': typeof JoinEnRoute
  '/$locale': typeof LocaleIndexRoute
  '/join': typeof JoinIndexRoute
  '/$locale/join/register': typeof LocaleJoinRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/$locale/join': typeof LocaleJoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/$locale/declare': typeof LocaleDeclareRoute
  '/$locale/home': typeof LocaleHomeRoute
  '/$locale/signin': typeof LocaleSigninRoute
  '/$locale/verify': typeof LocaleVerifyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/join/en': typeof JoinEnRoute
  '/$locale/': typeof LocaleIndexRoute
  '/join/': typeof JoinIndexRoute
  '/$locale/join/register': typeof LocaleJoinRegisterRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/$locale/join/': typeof LocaleJoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/mcp'
    | '/register'
    | '/$locale/declare'
    | '/$locale/home'
    | '/$locale/signin'
    | '/$locale/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/join/en'
    | '/$locale/'
    | '/join/'
    | '/$locale/join/register'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/$locale/join/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/register'
    | '/$locale/declare'
    | '/$locale/home'
    | '/$locale/signin'
    | '/$locale/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/join/en'
    | '/$locale'
    | '/join'
    | '/$locale/join/register'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/$locale/join'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/mcp'
    | '/register'
    | '/$locale/declare'
    | '/$locale/home'
    | '/$locale/signin'
    | '/$locale/verify'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/join/en'
    | '/$locale/'
    | '/join/'
    | '/$locale/join/register'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/$locale/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  JoinEnRoute: typeof JoinEnRoute
  JoinIndexRoute: typeof JoinIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/join/en': {
      id: '/join/en'
      path: '/join/en'
      fullPath: '/join/en'
      preLoaderRoute: typeof JoinEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/verify': {
      id: '/$locale/verify'
      path: '/verify'
      fullPath: '/$locale/verify'
      preLoaderRoute: typeof LocaleVerifyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/signin': {
      id: '/$locale/signin'
      path: '/signin'
      fullPath: '/$locale/signin'
      preLoaderRoute: typeof LocaleSigninRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/home': {
      id: '/$locale/home'
      path: '/home'
      fullPath: '/$locale/home'
      preLoaderRoute: typeof LocaleHomeRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/declare': {
      id: '/$locale/declare'
      path: '/declare'
      fullPath: '/$locale/declare'
      preLoaderRoute: typeof LocaleDeclareRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/join/': {
      id: '/$locale/join/'
      path: '/join'
      fullPath: '/$locale/join/'
      preLoaderRoute: typeof LocaleJoinIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/join/register': {
      id: '/$locale/join/register'
      path: '/join/register'
      fullPath: '/$locale/join/register'
      preLoaderRoute: typeof LocaleJoinRegisterRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleDeclareRoute: typeof LocaleDeclareRoute
  LocaleHomeRoute: typeof LocaleHomeRoute
  LocaleSigninRoute: typeof LocaleSigninRoute
  LocaleVerifyRoute: typeof LocaleVerifyRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleJoinRegisterRoute: typeof LocaleJoinRegisterRoute
  LocaleJoinIndexRoute: typeof LocaleJoinIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleDeclareRoute: LocaleDeclareRoute,
  LocaleHomeRoute: LocaleHomeRoute,
  LocaleSigninRoute: LocaleSigninRoute,
  LocaleVerifyRoute: LocaleVerifyRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleJoinRegisterRoute: LocaleJoinRegisterRoute,
  LocaleJoinIndexRoute: LocaleJoinIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  JoinEnRoute: JoinEnRoute,
  JoinIndexRoute: JoinIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
