create temporary table _mmda (slug text, region_slug text, name text, capital text) on commit drop;
insert into _mmda values
('asunafo-south','ahafo','Asunafo South','Kukuom'),('asunafo-north-municipal','ahafo','Asunafo North Municipal','Goaso'),('asutifi-south','ahafo','Asutifi South','Hwidiem'),('asutifi-north','ahafo','Asutifi North','Kenyasi'),('tano-south-municipal','ahafo','Tano South Municipal','Bechem'),('tano-north-municipal','ahafo','Tano North Municipal','Duayaw Nkwanta'),
('adansi-south','ashanti','Adansi South','New Edubiase'),('adansi-north','ashanti','Adansi North','Fomena'),('adansi-asokwa','ashanti','Adansi Asokwa','Adansi Asokwa'),('bekwai-municipal','ashanti','Bekwai Municipal','Bekwai'),('akrofuom','ashanti','Akrofuom','Akrofuom'),('obuasi-municipal','ashanti','Obuasi Municipal','Obuasi'),('obuasi-east','ashanti','Obuasi East','Tutuka'),('amansie-central','ashanti','Amansie Central','Jacobu'),('amansie-west','ashanti','Amansie West','Manso'),('amansie-south','ashanti','Amansie South','Edubia'),('ahafo-ano-southwest','ashanti','Ahafo Ano Southwest','Mankraso'),('ahafo-ano-southeast','ashanti','Ahafo Ano Southeast','Adugyama'),('ahafo-ano-north-municipal','ashanti','Ahafo Ano North Municipal','Tepa'),('atwima-mponua','ashanti','Atwima Mponua','Nyinahin'),('atwima-nwabiagya-south-municipal','ashanti','Atwima Nwabiagya South Municipal','Nkawie'),('atwima-kwanwoma','ashanti','Atwima Kwanwoma','Twedie'),('atwima-nwabiagya-north','ashanti','Atwima Nwabiagya North','Barekese'),('kumasi-metropolitan','ashanti','Kumasi Metropolitan','Kumasi'),('kwadaso-municipal','ashanti','Kwadaso Municipal','Kwadaso'),('tafo-municipal','ashanti','Tafo Municipal','Old Tafo'),('suame-municipal','ashanti','Suame Municipal','Suame'),('bosomtwe','ashanti','Bosomtwe','Kuntanase'),('asokwa-municipal','ashanti','Asokwa Municipal','Asokwa'),('oforikrom-municipal','ashanti','Oforikrom Municipal','Oforikrom'),('asokore-mampong-municipal','ashanti','Asokore Mampong Municipal','Asokore Mampong'),('kwabre-east-municipal','ashanti','Kwabre East Municipal','Mamponteng'),('juaben-municipal','ashanti','Juaben Municipal','Juaben'),('ejisu-municipal','ashanti','Ejisu Municipal','Ejisu'),('sekyere-east','ashanti','Sekyere East','Effiduase'),('sekyere-kumawu','ashanti','Sekyere Kumawu','Kumawu'),('sekyere-afram-plains','ashanti','Sekyere Afram Plains','Drobonso'),('sekyere-central','ashanti','Sekyere Central','Nsuta'),('sekyere-south','ashanti','Sekyere South','Agona'),('asante-akim-south-municipal','ashanti','Asante Akim South Municipal','Juaso'),('asante-akim-central-municipal','ashanti','Asante Akim Central Municipal','Konongo'),('asante-akim-north-municipal','ashanti','Asante Akim North Municipal','Agogo'),('bosome-freho','ashanti','Bosome Freho','Asiwa'),('mampong-municipal','ashanti','Mampong Municipal','Mampong'),('ejura-sekyedumase-municipal','ashanti','Ejura Sekyedumase Municipal','Ejura'),('afigya-kwabre-south','ashanti','Afigya Kwabre South','Kodie'),('afigya-kwabre-north','ashanti','Afigya Kwabre North','Boamang'),('offinso-municipal','ashanti','Offinso Municipal','Offinso'),('offinso-north','ashanti','Offinso North','Akomadan'),
('sunyani-east-municipal','bono','Sunyani East Municipal','Sunyani'),('sunyani-west-municipal','bono','Sunyani West Municipal','Odumasi'),('berekum-east-municipal','bono','Berekum East Municipal','Berekum'),('berekum-west','bono','Berekum West','Jinijini'),('dormaa-west','bono','Dormaa West','Nkrankwanta'),('dormaa-central-municipal','bono','Dormaa Central Municipal','Dormaa Ahenkro'),('dormaa-east','bono','Dormaa East','Wamfie'),('jaman-south-municipal','bono','Jaman South Municipal','Drobo'),('jaman-north','bono','Jaman North','Sampa'),('banda','bono','Banda','Banda Ahenkro'),('tain','bono','Tain','Nsawkaw'),('wenchi-municipal','bono','Wenchi Municipal','Wenchi'),
('techiman-municipal','bono-east','Techiman Municipal','Techiman'),('techiman-north','bono-east','Techiman North','Tuobodom'),('kintampo-north-municipal','bono-east','Kintampo North Municipal','Kintampo'),('kintampo-south','bono-east','Kintampo South','Jema'),('nkoranza-north','bono-east','Nkoranza North','Busunya'),('nkoranza-south-municipal','bono-east','Nkoranza South Municipal','Nkoranza'),('atebubu-amantin-municipal','bono-east','Atebubu-Amantin Municipal','Atebubu'),('pru-west','bono-east','Pru West','Prang'),('pru-east','bono-east','Pru East','Yeji'),('sene-west','bono-east','Sene West','Kwame Danso'),('sene-east','bono-east','Sene East','Kajaji'),
('komenda-edina-eguafo-abrem-municipal','central','Komenda Edina Eguafo Abrem Municipal','Elmina'),('cape-coast-metropolitan','central','Cape Coast Metropolitan','Cape Coast'),('mfantsiman-municipal','central','Mfantsiman Municipal','Saltpond'),('ekumfi','central','Ekumfi','Essarkyir'),('ajumako-enyan-esiam','central','Ajumako-Enyan-Esiam','Ajumako'),('gomoa-west','central','Gomoa West','Apam'),('gomoa-central','central','Gomoa Central','Afransi'),('gomoa-east','central','Gomoa East','Potsin'),('effutu-municipal','central','Effutu Municipal','Winneba'),('awutu-senya-west','central','Awutu Senya West','Awutu Breku'),('awutu-senya-east-municipal','central','Awutu Senya East Municipal','Kasoa'),('agona-west-municipal','central','Agona West Municipal','Swedru'),('agona-east','central','Agona East','Nsaba'),('asikuma-odoben-brakwa','central','Asikuma Odoben Brakwa','Breman Asikuma'),('abura-asebu-kwamankese','central','Abura-Asebu-Kwamankese','Abura Dunkwa'),('assin-central-municipal','central','Assin Central Municipal','Assin Fosu'),('assin-north','central','Assin North','Assin Bereku'),('assin-south','central','Assin South','Nsuaem Kyekyewere'),('twifo-ati-morkwa','central','Twifo Ati Morkwa','Twifo Praso'),('twifo-hemang-lower-denkyira','central','Twifo Hemang Lower Denkyira','Hemang'),('upper-denkyira-east-municipal','central','Upper Denkyira East Municipal','Dunkwa-on-Offin'),('upper-denkyira-west','central','Upper Denkyira West','Diaso'),
('asuogyaman','eastern','Asuogyaman','Atimpoku'),('lower-manya-krobo-municipal','eastern','Lower Manya Krobo Municipal','Odumase Krobo'),('upper-manya-krobo','eastern','Upper Manya Krobo','Asesewa'),('yilo-krobo-municipal','eastern','Yilo Krobo Municipal','Somanya'),('new-juaben-south-municipal','eastern','New Juaben South Municipal','Koforidua'),('new-juaben-north-municipal','eastern','New Juaben North Municipal','Effiduase'),('akwapim-north-municipal','eastern','Akwapim North Municipal','Akropong'),('okere','eastern','Okere','Adukrom'),('akuapem-south','eastern','Akuapem South','Aburi'),('nsawam-adoagyiri-municipal','eastern','Nsawam Adoagyiri Municipal','Nsawam'),('suhum-municipal','eastern','Suhum Municipal','Suhum'),('ayensuano','eastern','Ayensuano','Coaltar'),('west-akim-municipal','eastern','West Akim Municipal','Asamankese'),('upper-west-akim','eastern','Upper West Akim','Adeiso'),('birim-central-municipal','eastern','Birim Central Municipal','Akim Oda'),('asene-manso-akroso','eastern','Asene Manso Akroso','Manso'),('birim-south','eastern','Birim South','Akim Swedru'),('achiase','eastern','Achiase','Achiase'),('akyemansa','eastern','Akyemansa','Ofoase'),('kwaebibirem-municipal','eastern','Kwaebibirem Municipal','Kade'),('denkyembuo','eastern','Denkyembuo','Akwatia'),('birim-north','eastern','Birim North','New Abirem'),('abuakwa-south-municipal','eastern','Abuakwa South Municipal','Kibi'),('abuakwa-north-municipal','eastern','Abuakwa North Municipal','Kukurantumi'),('atiwa-west','eastern','Atiwa West','Kwabeng'),('atiwa-east','eastern','Atiwa East','Anyinam'),('fanteakwa-north','eastern','Fanteakwa North','Begoro'),('fanteakwa-south','eastern','Fanteakwa South','Osino'),('kwahu-west-municipal','eastern','Kwahu West Municipal','Nkawkaw'),('kwahu-south-municipal','eastern','Kwahu South Municipal','Mpraeso'),('kwahu-east','eastern','Kwahu East','Abetifi'),('afram-plains-north','eastern','Afram Plains North','Donkorkrom'),('afram-plains-south','eastern','Afram Plains South','Tease'),
('ga-south-municipal','greater-accra','Ga South Municipal','Ngleshie Amanfrom'),('weija-gbawe-municipal','greater-accra','Weija Gbawe Municipal','Weija'),('ga-central-municipal','greater-accra','Ga Central Municipal','Sowutuom'),('ga-north-municipal','greater-accra','Ga North Municipal','Ofankor'),('ga-west-municipal','greater-accra','Ga West Municipal','Amasaman'),('ga-east-municipal','greater-accra','Ga East Municipal','Abokobi'),('la-nkwantanang-madina-municipal','greater-accra','La Nkwantanang Madina Municipal','Madina'),('ayawaso-east-municipal','greater-accra','Ayawaso East Municipal','Nima'),('ayawaso-north-municipal','greater-accra','Ayawaso North Municipal','Accra Newtown'),('ayawaso-central-municipal','greater-accra','Ayawaso Central Municipal','Kokomlemle'),('ayawaso-west-municipal','greater-accra','Ayawaso West Municipal','Dzorwulu'),('accra-metropolitan','greater-accra','Accra Metropolitan','Accra'),('okaikwei-north-municipal','greater-accra','Okaikwei North Municipal','Abeka'),('ablekuma-north-municipal','greater-accra','Ablekuma North Municipal','Darkuman'),('ablekuma-central-municipal','greater-accra','Ablekuma Central Municipal','Lartebiokorshie'),('ablekuma-west-municipal','greater-accra','Ablekuma West Municipal','Dansoman'),('korle-klottey-municipal','greater-accra','Korle Klottey Municipal','Osu'),('la-dade-kotopon-municipal','greater-accra','La Dade-Kotopon Municipal','La'),('ledzokuku-municipal','greater-accra','Ledzokuku Municipal','Teshie'),('krowor-municipal','greater-accra','Krowor Municipal','Nungua'),('tema-metropolitan','greater-accra','Tema Metropolitan','Tema'),('tema-west-municipal','greater-accra','Tema West Municipal','Tema Community 2'),('kpone-katamanso-municipal','greater-accra','Kpone Katamanso Municipal','Kpone'),('ashaiman-municipal','greater-accra','Ashaiman Municipal','Ashaiman'),('adentan-municipal','greater-accra','Adentan Municipal','Adentan'),('shai-osudoku','greater-accra','Shai-Osudoku','Dodowa'),('ningo-prampram','greater-accra','Ningo-Prampram','Prampram'),('ada-west','greater-accra','Ada West','Sege'),('ada-east','greater-accra','Ada East','Ada Foah'),
('west-mamprusi-municipal','north-east','West Mamprusi Municipal','Walewale'),('mamprugu-moagduri','north-east','Mamprugu-Moagduri','Yagaba'),('east-mamprusi-municipal','north-east','East Mamprusi Municipal','Gambaga'),('bunkpurugu-nakpanduri','north-east','Bunkpurugu-Nakpanduri','Bunkpurugu'),('yunyoo-nasuan','north-east','Yunyoo-Nasuan','Yunyoo'),('chereponi','north-east','Chereponi','Chereponi'),
('kpandai','northern','Kpandai','Kpandai'),('nanumba-north-municipal','northern','Nanumba North Municipal','Bimbilla'),('nanumba-south','northern','Nanumba South','Wulensi'),('zabzugu','northern','Zabzugu','Zabzugu'),('tatale-sanguli','northern','Tatale Sanguli','Tatale'),('yendi-municipal','northern','Yendi Municipal','Yendi'),('mion','northern','Mion','Sang'),('saboba','northern','Saboba','Saboba'),('gushegu-municipal','northern','Gushegu Municipal','Gushegu'),('karaga','northern','Karaga','Karaga'),('savelugu-municipal','northern','Savelugu Municipal','Savelugu'),('nanton','northern','Nanton','Nanton'),('tamale-metropolitan','northern','Tamale Metropolitan','Tamale'),('sagnarigu-municipal','northern','Sagnarigu Municipal','Sagnarigu'),('tolon','northern','Tolon','Tolon'),('kumbungu','northern','Kumbungu','Kumbungu'),
('jasikan-municipal','oti','Jasikan Municipal','Jasikan'),('kadjebi','oti','Kadjebi','Kadjebi'),('nkwanta-south-municipal','oti','Nkwanta South Municipal','Nkwanta'),('nkwanta-north','oti','Nkwanta North','Kpasa'),('biakoye','oti','Biakoye','Nkonya Ahenkro'),('krachi-east-municipal','oti','Krachi East Municipal','Dambai'),('krachi-west-municipal','oti','Krachi West Municipal','Kete Krachi'),('krachi-nchumuru','oti','Krachi-Nchumuru','Chinderi'),('guan','oti','Guan','Likpe Mate'),
('bole','savannah','Bole','Bole'),('sawla-tuna-kalba','savannah','Sawla-Tuna-Kalba','Sawla'),('west-gonja-municipal','savannah','West Gonja Municipal','Damongo'),('north-gonja','savannah','North Gonja','Daboya'),('central-gonja','savannah','Central Gonja','Buipe'),('east-gonja-municipal','savannah','East Gonja Municipal','Salaga'),('north-east-gonja','savannah','North East Gonja','Kpalbe'),
('builsa-south','upper-east','Builsa South','Fumbisi'),('builsa-north-municipal','upper-east','Builsa North Municipal','Sandema'),('kassena-nankana-municipal','upper-east','Kassena-Nankana Municipal','Navrongo'),('kassena-nankana-west','upper-east','Kassena-Nankana West','Paga'),('bolgatanga-municipal','upper-east','Bolgatanga Municipal','Bolgatanga'),('bolgatanga-east','upper-east','Bolgatanga East','Zuarungu'),('bongo','upper-east','Bongo','Bongo'),('talensi','upper-east','Talensi','Tongo'),('nabdam','upper-east','Nabdam','Nangodi'),('bawku-west','upper-east','Bawku West','Zebilla'),('bawku-municipal','upper-east','Bawku Municipal','Bawku'),('pusiga','upper-east','Pusiga','Pusiga'),('garu','upper-east','Garu','Garu'),('tempane','upper-east','Tempane','Tempane'),('binduri','upper-east','Binduri','Binduri'),
('wa-municipal','upper-west','Wa Municipal','Wa'),('wa-west','upper-west','Wa West','Wechiau'),('nadowli-kaleo','upper-west','Nadowli-Kaleo','Nadowli'),('daffiama-bussie-issa','upper-west','Daffiama-Bussie-Issa','Issa'),('jirapa-municipal','upper-west','Jirapa Municipal','Jirapa'),('lambussie','upper-west','Lambussie','Lambussie'),('lawra-municipal','upper-west','Lawra Municipal','Lawra'),('nandom','upper-west','Nandom','Nandom'),('wa-east','upper-west','Wa East','Funsi'),('sissala-west','upper-west','Sissala West','Gwollu'),('sissala-east-municipal','upper-west','Sissala East Municipal','Tumu'),
('keta-municipal','volta','Keta Municipal','Keta'),('anloga','volta','Anloga','Anloga'),('ketu-south-municipal','volta','Ketu South Municipal','Denu'),('ketu-north-municipal','volta','Ketu North Municipal','Dzodze'),('akatsi-south','volta','Akatsi South','Akatsi'),('akatsi-north','volta','Akatsi North','Ave Dakpa'),('south-tongu','volta','South Tongu','Sogakope'),('central-tongu','volta','Central Tongu','Adidome'),('north-tongu','volta','North Tongu','Battor'),('adaklu','volta','Adaklu','Adaklu Waya'),('agotime-ziope','volta','Agotime-Ziope','Agotime Kpetoe'),('ho-municipal','volta','Ho Municipal','Ho'),('ho-west','volta','Ho West','Dzolokpuita'),('south-dayi','volta','South Dayi','Kpeve'),('kpando-municipal','volta','Kpando Municipal','Kpando'),('north-dayi','volta','North Dayi','Anfoega'),('hohoe-municipal','volta','Hohoe Municipal','Hohoe'),('afadjato-south','volta','Afadjato South','Ve-Golokwati'),
('jomoro-municipal','western','Jomoro Municipal','Half Assini'),('ellembele','western','Ellembele','Nkroful'),('nzema-east-municipal','western','Nzema East Municipal','Axim'),('ahanta-west-municipal','western','Ahanta West Municipal','Agona Nkwanta'),('sekondi-takoradi-metropolitan','western','Sekondi Takoradi Metropolitan','Sekondi'),('effia-kwesimintsim-municipal','western','Effia-Kwesimintsim Municipal','Kwesimintsim'),('shama','western','Shama','Shama'),('wassa-east','western','Wassa East','Daboase'),('mpohor','western','Mpohor','Mpohor'),('tarkwa-nsuaem-municipal','western','Tarkwa Nsuaem Municipal','Tarkwa'),('prestea-huni-valley-municipal','western','Prestea Huni-Valley Municipal','Bogoso'),('amenfi-east-municipal','western','Amenfi East Municipal','Wassa Akropong'),('amenfi-central','western','Amenfi Central','Manso Amenfi'),('amenfi-west-municipal','western','Amenfi West Municipal','Asankragua'),
('aowin-municipal','western-north','Aowin Municipal','Enchi'),('suaman','western-north','Suaman','Dadieso'),('bibiani-anhwiaso-bekwai-municipal','western-north','Bibiani-Anhwiaso-Bekwai Municipal','Bibiani'),('sefwi-wiawso-municipal','western-north','Sefwi Wiawso Municipal','Sefwi Wiawso'),('sefwi-akontombra','western-north','Sefwi Akontombra','Sefwi Akontombra'),('juaboso','western-north','Juaboso','Juaboso'),('bodi','western-north','Bodi','Bodie'),('bia-west','western-north','Bia West','Essam-Dabiso'),('bia-east','western-north','Bia East','Adabokrom');

update public.places set slug = 'akatsi-south' where slug = 'akatsi-south-municipal';

update public.places p
   set name = m.name, capital = m.capital,
       url_path = m.region_slug || '/' || m.slug,
       data_confidence = 'Sourced',
       reference_source = 'Inter-Ministerial Coordinating Committee on Decentralisation (imccod.gov.gh/mmdas)',
       reference_verified = date '2026-08-29'
  from _mmda m
 where p.slug = m.slug and p.type_slug = 'district';

insert into public.places (slug, type_slug, url_path, name, capital, data_confidence, reference_source, reference_verified)
select m.slug, 'district', m.region_slug || '/' || m.slug, m.name, m.capital, 'Sourced',
       'Inter-Ministerial Coordinating Committee on Decentralisation (imccod.gov.gh/mmdas)', date '2026-08-29'
  from _mmda m
 where not exists (select 1 from public.places p where p.slug = m.slug);

insert into public.place_links (parent_slug, child_slug, link_type_slug)
select m.region_slug, m.slug, 'administrative'
  from _mmda m
 where not exists (select 1 from public.place_links l where l.child_slug = m.slug and l.link_type_slug = 'administrative');
